import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ClientSidebar from "./components/ClientSidebar";

const font = Poppins({ subsets: ["latin"], weight: ["100", "200"] });

export const metadata: Metadata = {
  title: "Fertilogy WebApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientSidebar />
        {children}
      </body>
    </html>
  );
}
